Count Negative Numbers in a Sorted Matrix
OlegCherep/Algo pull request #21
Opened 2022-03-06 13:11 UTC by OlegCherep

Возвращает количество отрицательных чисел в матрице.
Ссылка: https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/

2022-03-06 13:22 UTC, vitkarpov requested changes
Решение рабочее, но требует O(N * M) операций (где N количество элементов по горизонтали, а M - по вертикали, или наоборот), так как тебе нужно проверить все клеточки в матрице.

Предлагаю подумать над решением O(N + M). Прикол в том, что элементы отсортированы, то есть отрицательные числа у тебя тяготеют к правому нижнему углу.

![image](https://user-images.githubusercontent.com/3001791/156925088-2fbffeb4-1984-47f2-84c5-9b48020270ad.png)

2022-03-06 13:41 UTC, OlegCherep commented
Ага, понял, сейчас подумаю над этим.

2022-03-12 18:29 UTC, vitkarpov commented
Текущее решение – бежать по всем строкам и столбцам, и считать сколько там отрицательный чисел. Однако, как видно на картинке выше, у тебя в каждой строке есть отсечка, после которой бежать до конца строки смысла нет. То есть как только ты встретил первое отрицательное число, ты понимаешь, что и дальше будут только отрицательные числа. Соответственно, ты можешь бежать по каждой строке, как и сейчас, только не до конца, а до отсечки, а дальше все просто: количество элементов в строке минус позиция отсечки это количество отрицательных чисел и есть, то есть те, что в хвосте, после отсечки.

2022-03-13 16:00 UTC, vitkarpov approved these changes
👏

2022-03-13 19:09 UTC, merged