N-Repeated Element in Size 2N Array
OlegCherep/Algo pull request #26
Opened 2022-03-06 13:35 UTC by OlegCherep

Возвращает элемент массива, который повторяется более одного раза.
Ссылка: https://leetcode.com/problems/n-repeated-element-in-size-2n-array/

2022-03-06 18:40 UTC, vitkarpov requested changes
Хорошее решение, лаконично. Однако, сложность O(N * log N) т.к. требуется отсортировать массив.

Если есть желание, предлагаю подумать над решением O(N), где не нужно сортировать.

Очевидно, можно обойтись подсчетом всех элементов, но это потребует так же дополнительной памяти, так как нужно где-то хранить.

Интуиция такая. Так как у тебя есть ровно N повторяющихся элементов в массиве длиной 2 * N, то есть по сути половина массива должна быть забита нужным тебе элементом.

Соответственно, если посмотреть на пары, то может быть два вариант:

- [x*][x*]
- [x*][*x]

где * нужны тебе элемент. Потому что иначе не может быть: если есть хоть одна пара соседей где нет нужного элемента, то не получится так что * повторяется ровно половину раз от всей длины массива.

Используя это доказательство, получится ли написать решение быстрее?

2022-03-06 18:42 UTC, vitkarpov commented
Более формальное доказательство от противного.

Допустим есть такая пара, которая не содержит нужного элемента (обозначим его звездочкой). Тогда общее количество элементов должно быть не больше `N / 2 - 1`. А это противоречит условию, что * содержится в массиве ровно N раз. Следовательно, нет такой пары.

ЧТД.

2022-03-06 22:37 UTC, OlegCherep commented
> Хорошее решение, лаконично. Однако, сложность O(N * log N) т.к. требуется отсортировать массив.
> 
> Если есть желание, предлагаю подумать над решением O(N), где не нужно сортировать.
> 
> Очевидно, можно обойтись подсчетом всех элементов, но это потребует так же дополнительной памяти, так как нужно где-то хранить.
> 
> Интуиция такая. Так как у тебя есть ровно N повторяющихся элементов в массиве длиной 2 * N, то есть по сути половина массива должна быть забита нужным тебе элементом.
> 
> Соответственно, если посмотреть на пары, то может быть два вариант:
> 
> * [x*][x*]
> * [x*][*x]
> 
> где * нужны тебе элемент. Потому что иначе не может быть: если есть хоть одна пара соседей где нет нужного элемента, то не получится так что * повторяется ровно половину раз от всей длины массива.
> 
> Используя это доказательство, получится ли написать решение быстрее?

Я надеюсь я правильно понял. Если что - поправь)
Т.е. можно сравнивать текущий элемент со следующим элементом  и элементом, стоящим через одного (типа если текущий элемент n[i], то можно сравнивать с n[i+1] и n[i+2]). Я реализовал это, но появилась такая последовательность: [9, 5, 6, 9], т.е. получилась пара [*x][x*], поэтому я как понял нужно сравнивать ещё и с элементом, идущим через два следующих элемента(типа n[i+3]). Реализовав такой метод у меня всё заработало, однако не все элементы тогда попадали под последовательность, поэтому в начале я два раза добавил в список строковое значение Х. Если непонятно описал, то опять напиши, постараюсь понятнее написать))) А пока вот, что получилось(надеюсь ты это имел ввиду):

            class Solution:
                def repeatedNTimes(self, nums: List[int]) -> int:
                    nums.append('x')
                    nums.append('x')
                    for i in range(len(nums)-3):
                        if (nums[i] == nums[i+1]) or (nums[i] == nums[i+2]) or (nums[i] == nums[i+3]):
                            return nums[i]

2022-03-07 07:48 UTC, vitkarpov commented
>  [* x][x *]

Да, я в своих выкладках забыл про вот такую комбинацию. Получается, что надо искать среди четырех элементов, ты верно сравниваешь.

2022-03-07 07:50 UTC, vitkarpov commented
> однако не все элементы тогда попадали под последовательность, поэтому в начале я два раза добавил в список строковое значение Х.

Про такое я не думал, а сравнивал с конца: последний элемент с тремя предыдущими. А зачем там в начале нужны x? Почему нельзя сравнивать первый элемент с тремя последующими, например?

2022-03-07 07:54 UTC, vitkarpov commented
> Про такое я не думал, а сравнивал с конца: последний элемент с тремя предыдущими.

Точнее не так. Надо сравнить сперва всех соседей, потом через один, потом через два, потом через три. И получится рано или поздно ты попадешь на случай когда числа равны.

2022-03-07 19:50 UTC, OlegCherep commented
> > однако не все элементы тогда попадали под последовательность, поэтому в начале я два раза добавил в список строковое значение Х.
> 
> Про такое я не думал, а сравнивал с конца: последний элемент с тремя предыдущими. А зачем там в начале нужны x? Почему нельзя сравнивать первый элемент с тремя последующими, например?

Точнее я имел ввиду в конец списка. Потому что у меня был пример последовательности [1, 2, 3, 3]. Если бы я не поставил Х, то программа бы просто сравнила единицу с двойкой и двумя тройками и всё, а так она ещё сравнит двойку с двумя тройками и тройку с тройкой (сравнивать Х она не будет, так как они другого типа данных). Я вот так думал.

2022-03-07 19:51 UTC, OlegCherep commented
> > Про такое я не думал, а сравнивал с конца: последний элемент с тремя предыдущими.
> 
> Точнее не так. Надо сравнить сперва всех соседей, потом через один, потом через два, потом через три. И получится рано или поздно ты попадешь на случай когда числа равны.

А, или ты имеешь ввиду,

2022-03-07 19:51 UTC, closed without merging

2022-03-08 18:49 UTC, vitkarpov commented
> сравнивать Х она не будет, так как они другого типа данных

Нормас, любопытное решение. Не думал про это.